import bcrypt from 'bcryptjs'

export const data = {
  users: [
    {
      name: 'John',
      email: 'admin@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Jane',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'Retro High-Tops',
      slug: 'retro_high_tops',
      category: 'Mens',
      image: '/images/retro_high_tops.jpg',
      price: 80,
      brand: 'Niko',
      rating: 4.0,
      numReviews: 5,
      qtyInStock: 20,
      description: 'Retro style athletic high-tops',
    },
    {
      name: 'NB Pinks',
      slug: 'nb_pinks',
      category: 'Womens',
      image: '/images/nb_pinks.jpg',
      price: 90,
      brand: 'New Bolance',
      rating: 4.2,
      numReviews: 4,
      qtyInStock: 10,
      description: 'Super stylish and comfortable',
    },
    {
      name: 'Classic Pumus',
      slug: 'classic_pumus',
      category: 'Mens',
      image: '/images/classic_pumus.jpg',
      price: 60,
      brand: 'Pumu',
      rating: 4.4,
      numReviews: 7,
      qtyInStock: 10,
      description: 'Classic style low-tops from Pumu',
    },
    {
      name: 'Chuck Tylers',
      slug: 'chuck_tylers',
      category: 'Unisex',
      image: '/images/chuck_tylers.jpg',
      price: 70,
      brand: 'Conversa',
      rating: 5.0,
      numReviews: 10,
      qtyInStock: 8,
      description: 'The one and only original Chucks',
    },
    {
      name: 'Yellow Docs',
      slug: 'yellow_docs',
      category: 'Unisex',
      image: '/images/yellow_docs.jpg',
      price: 130,
      brand: 'Doc Martiens',
      rating: 3.9,
      numReviews: 3,
      qtyInStock: 5,
      description: 'Stylish and functional',
    },
    {
      name: 'Vams Mid-Top',
      slug: 'vams_mid_top',
      category: 'Womens',
      image: '/images/vams_mid_top.jpg',
      price: 75,
      brand: 'Vams',
      rating: 4.6,
      numReviews: 6,
      qtyInStock: 12,
      description: 'Super fashionalble skate or casual',
    },
  ],
}
